# Generated by Django 3.2.7 on 2021-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='images/'),
        ),
    ]
